### ISSUE TITLE
reduce vertical real estate

### ISSUE THREAD

**Issue by sebdalgarno** [bcgov/msw-disposal-indicator#10]
from Andy:
A couple of thoughts... on the bottom chart, the population and disposal rate could be shown on the same line. Do you think the 'Resources' buttons could be to the right of the chart or would that squish it too much? I think at the very least they should be below the chart so the chart takes visual precedence

**Comment by sebdalgarno** [comment]
done. I put the download buttons at bottom and moved pop/rate/show BC to a single line...also reduced the size of upper plot by 50px

**Comment by ateucher** [comment]
Sorry, just going to reopen this quickly. Looking great, but the text on the legend of the top bar chart is a bit too tiny (for space reasons I know). Maybe you could make more space by instead of having two legend entries with 'Population' spelled out in full, it could have a title 'Population:' and the two labels be `> 100,000` and `< 100,000`

**Comment by sebdalgarno** [comment]
no worries! that's a good idea...will implement

**Comment by sebdalgarno** [comment]
I've made the legend text size same as the axis text size...all of which is controlled in the global variable `txt_size`, so easy to change later.

**Comment by sebdalgarno** [comment]
better? bigger?

**Comment by sebdalgarno** [comment]
I've pushed those changes, if you want to take a peak

**Comment by ateucher** [comment]
Looks great!
